"""Port interfaces for the synth_data domain."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Protocol, runtime_checkable


class DataGenerator(Protocol):
    """Port for synthetic data generation.

    Implementations can use Faker, LLMs, or any other data source.
    The matching module maps column names/types to these methods.
    """

    def word(self) -> str: ...
    def words(self, nb: int = 3) -> list[str]: ...
    def name(self) -> str: ...
    def first_name(self) -> str: ...
    def last_name(self) -> str: ...
    def email(self) -> str: ...
    def phone_number(self) -> str: ...
    def street_address(self) -> str: ...
    def city(self) -> str: ...
    def province(self) -> str: ...
    def postcode(self) -> str: ...
    def country(self) -> str: ...
    def country_code(self) -> str: ...
    def latitude(self) -> str: ...
    def longitude(self) -> str: ...
    def company(self) -> str: ...
    def job(self) -> str: ...
    def pyfloat(self, min_value: float = 0, max_value: float = 1) -> float: ...
    def pyint(self, min_value: int = 0, max_value: int = 1) -> int: ...
    def credit_card_number(self) -> str: ...
    def iban(self) -> str: ...
    def currency_code(self) -> str: ...
    def ssn(self) -> str: ...
    def uuid4(self) -> str: ...
    def isbn13(self) -> str: ...
    def mac_address(self) -> str: ...
    def date_time_between(self, start_date: str = "-30y", end_date: str = "now") -> Any: ...
    def date_between(self, start_date: str = "-30y", end_date: str = "today") -> Any: ...
    def year(self) -> str: ...
    def month(self) -> str: ...
    def url(self) -> str: ...
    def domain_name(self) -> str: ...
    def ipv4(self) -> str: ...
    def slug(self) -> str: ...
    def password(self) -> str: ...
    def sha256(self) -> str: ...
    def mime_type(self) -> str: ...
    def file_extension(self) -> str: ...
    def timezone(self) -> str: ...
    def sentence(self) -> str: ...
    def paragraph(self) -> str: ...
    def hex_color(self) -> str: ...
    def binary(self, length: int = 10) -> Any: ...
    def json(self) -> str: ...
    def xml(self) -> str: ...
    def text(self, max_nb_chars: int = 200) -> str: ...
    def time_object(self) -> Any: ...


@runtime_checkable
class Database(Protocol):
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Database: ...
    def __exit__(self, *args: Any) -> None: ...
    def list_databases(self) -> list[str]: ...
    def list_tables(self, database: str) -> list[dict[str, str]]: ...
    def table_exists(self, database: str, table: str) -> bool: ...
    def column_exists(self, database: str, table: str, column: str) -> bool: ...
    def get_columns(self, database: str, table: str) -> Sequence[tuple[Any, ...]]: ...
    def get_column_names(self, database: str, table: str) -> list[str]: ...
    def read_table(self, database: str, table: str, limit: int = 20) -> list[tuple]: ...
    def read_column_values(self, database: str, table: str, column: str) -> list[Any]: ...
    def get_foreign_keys(self, database: str, table: str) -> list[dict[str, str]]: ...
    def insert_fake_rows(
        self,
        database: str,
        table: str,
        columns: Sequence[tuple[Any, ...]],
        num_rows: int = 100,
        batch_size: int = 50,
        fk_overrides: dict[str, list[Any]] | None = None,
    ) -> int: ...
    def seed_all(self, database: str, num_rows: int = 100) -> list[tuple[str, int, str]]: ...
    def seed_with_relations(
        self,
        database: str,
        seed_order: list[tuple[str, int]],
        fk_map: dict[str, dict[str, tuple[str, str]]],
    ) -> list[tuple[str, int, str]]: ...
    def create_schema(self, database: str, schema_module: Any = None) -> list[str]: ...
    def drop_schema(self, database: str, schema_module: Any = None) -> list[str]: ...
    def purge_data(self, database: str) -> list[str]: ...
